enum Permission {
  checkOthersIn,
  viewActiveAlerts,
  viewPastAlerts,
  clearAlarms,
  acceptAlerts,
  acceptMultipleAlerts,
  editProfile,
  login,
  viewEvents,
  registerForEvents,
  markAbsentStatus,
  checkIn,
  triggerAlarms,
  viewDocsImages,
  downloadReportsOfPastAlerts,
}
